// Shared sample inputs + expected result substrings for tool tests.
// Used by the vitest ToolRunner suite (jsdom) and the Playwright flows spec.
// Values must satisfy each tool's validate() — they mirror catalog.test.ts.
export const TOOL_SAMPLES: Record<string, Record<string, string>> = {
  "bmi-calculator": { weightKg: "75", heightCm: "180" },
  "age-calculator": { birthDate: "1990-01-15", asOfDate: "2026-09-14" },
  "tip-calculator": { billAmount: "100", tipPercent: "15", people: "2" },
  "loan-calculator": { principal: "200000", annualRatePercent: "5", years: "30", loanType: "home", currency: "USD" },
  "percentage-calculator": { value: "20", total: "200", oldValue: "150" },
  "compound-interest-calculator": { principal: "10000", rate: "5", years: "10", compoundsPerYear: "12" },
  "roi-calculator": { gain: "15000", cost: "10000" },
  "discount-calculator": { price: "100", discount: "25" },
  "vat-calculator": { amount: "100", rate: "20", mode: "add" },
  "unit-converter": { value: "10", from: "km", to: "mi" },
  "date-difference-calculator": { from: "2026-01-01", to: "2026-09-12" },
  "json-formatter": { json: '{"b":2,"a":1}', indent: "2" },
  "json-minifier": { json: '{ "a": 1, "b": 2 }' },
  "json-validator": { json: "[1,2,3]" },
  "json-to-yaml": { json: '{"name":"Rovo","free":true}' },
  "yaml-to-json": { yaml: "name: Rovo\nfree: true\ncount: 3" },
  "json-to-typescript": { json: '{"name":"Rovo","users":5}', name: "Site" },
  "csv-to-json": { csv: "name,age\nAda,36\nGrace,85" },
  "json-to-csv": { json: '[{"name":"Ada","age":36}]' },
  "base64-encoder": { text: "Hello RovoTools" },
  "base64-decoder": { base64: "SGVsbG8gUm92b1Rvb2xz" },
  "url-encoder": { text: "hello world?&=" },
  "url-decoder": { text: "hello%20world%3F%26%3D" },
  "jwt-decoder": {
    token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  },
  "regex-tester": { pattern: "\\d+", flags: "g", text: "abc 123 def 456" },
  "diff-checker": { original: "line1\nline2", modified: "line1\nline3" },
  "uuid-generator": { count: "3" },
  "timestamp-converter": { value: "1726000000" },
  "word-counter": { text: "Hello world. This is a test." },
  "character-counter": { text: "Hello!" },
  "case-converter": { text: "hello world test" },
  "duplicate-line-remover": { text: "a\nb\na\nc", caseSensitive: "true" },
  "empty-line-remover": { text: "a\n\nb\n   \nc", trim: "true" },
  "text-cleaner": { text: "  too   many    spaces  \n\n\nnext" },
  "slug-generator": { title: "Hello World: A Test Post!" },
  "lorem-ipsum-generator": { count: "2", unit: "paragraphs" },
  "reading-time-calculator": { text: "word ".repeat(400), wpm: "200" },
  "password-generator": { length: "16", upper: "true", digits: "true", symbols: "false" },
  "password-strength-checker": { password: "Tr0ub4dor&3" },
  "hash-generator": { text: "hello" },
  "random-token-generator": { bytes: "16" },
  "hex-encoder": { text: "hello", mode: "encode" },
  "css-gradient-generator": { from: "#4f46e5", to: "#ec4899", angle: "135" },
  "css-box-shadow-generator": { x: "0", y: "8", blur: "24", spread: "0", color: "rgba(0,0,0,0.15)" },
  "css-border-radius-generator": { all: "12", topLeft: "", topRight: "", bottomRight: "", bottomLeft: "" },
  "css-button-generator": { bg: "#4f46e5", color: "#ffffff", padding: "12px 24px", radius: "8" },
  "color-converter": { color: "#4f46e5" },
  "color-contrast-checker": { foreground: "#000000", background: "#ffffff" },
  "url-qr-generator": { url: "https://rovotools.com" },
  "wifi-qr-generator": { ssid: "HomeNet", password: "secret123", security: "WPA" },
  "vcard-qr-generator": { name: "Ada Lovelace", phone: "+123", email: "ada@example.com", org: "RovoCorp" },
  "text-qr-generator": { text: "Hello QR" },
  "text-to-pdf": { text: "Hello PDF world" },
  "pdf-creator": { text: "Hello PDF world", title: "Hello" },
  "meta-tag-generator": {
    title: "Test Page Title Here For SEO",
    description: "A concise meta description for testing purposes, within ideal length bounds here.",
    url: "https://rovotools.com/test",
  },
  "svg-placeholder-generator": { width: "600", height: "400", bg: "#e5e7eb", fg: "#6b7280", label: "600 x 400" },
  "average-calculator": { numbers: "1, 2, 3, 4, 5" },
  "email-validator": { email: "ada@example.com" },
  "url-validator": { url: "https://rovotools.com/tools" },
  "number-formatter": { value: "1234567.891", decimals: "2", locale: "en-US" },
  "date-formatter": { date: "2026-09-12" },
  "random-number-generator": { min: "1", max: "100", count: "3" },
  "code-minifier": { code: "function add( a, b ) { // sum\n  return a + b;\n}", language: "js", mode: "minify" },
  "keyword-density-checker": {
    text: "Dogs are great. Dogs love walks. Cats are great too. Dogs and cats play.",
    top: "5",
    maxWords: "2",
  },
  "robots-txt-generator": {
    preset: "wordpress",
    sitemap: "https://example.com/sitemap.xml",
    disallow: "/private\ntmp",
    allow: "",
  },
  "adsense-earnings-calculator": {
    pageviews: "100000",
    mode: "ctr-cpc",
    ctr: "1.5",
    cpc: "0.25",
    rpm: "",
    currency: "USD",
  },
  "tax-calculator": { amount: "1000", region: "india", rate: "18", customRate: "", mode: "add" },
  "youtube-thumbnail-downloader": { url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
};

// Deterministic spot-checks on rendered result text.
export const EXPECTED_SUBSTRINGS: Record<string, Array<string>> = {
  "bmi-calculator": ["23.1"],
  "tip-calculator": ["15", "115"],
  "base64-encoder": ["SGVsbG8gUm92b1Rvb2xz"],
  "base64-decoder": ["Hello RovoTools"],
  "word-counter": ["6"],
  "slug-generator": ["hello-world-a-test-post"],
};
